compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
fsdp_config:
  fsdp_activation_checkpointing: false
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_cls_to_wrap: 'PixArtTransformer2DModel'
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: false
  fsdp_forward_prefetch: true
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
# dynamo_config:
# dynamo_backend: 'inductor'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
use_cpu: false
