project_name: '512'
exp_name: '512step2'
model:
  flashSA:  'Joint_SA'  # choose from [ None,  'Joint_SA' ]
  caption_max_seq_length: 128

training:
  save_freq: 10000
  max_iters: 50000
  transformer_ckpt: '512step1/checkpoints/checkpoint-50/model.safetensors' #change here ckpt path when finetune step1
  use_ema: True
  
dataset:
  precompute_txt_emb: False
  precompute_dino_feat: False
  datasets: [
            'datasets/prepare/datadir/mds/mds_train_512diffdb_fromflux', #The entire dataset takes up approximately 60+ GB
            'datasets/prepare/datadir/mds/mds_train_512ucsc_fromflux', #The entire dataset takes up approximately 80+ GB
            'datasets/prepare/datadir/mds/mds_train_512jdb', #The entire dataset takes up approximately 200+ GB
            'datasets/prepare/datadir/mds/mds_train_512sa1b', #The entire dataset takes up approximately 600+ GB
            ]
