#  Copyright (C) 2026 Advanced Micro Devices, Inc. All rights Reserved.

project_name: nitroAR
work_root: nitroAR
exp_name: nitroAR_gan
llama_path: meta-llama/Llama-3.2-1B
model:
  flashSA: Joint_SA
  patch_size: 1
  latent_size: 16
  in_channels: 32
  out_channels: 32
  caption_max_seq_length: 128
  caption_channels: 2048
  arch: emmdit_nosub
  diffloss_d: 8
  diffloss_w: 768
  num_sampling_steps: 1000
  diffusion_batch_mul: 2
  repa_depth: -1
  projector_dim: 2048
  z_dims:
  - 768
training:
  gradient_accumulation_steps: 1
  train_batch_size: 256
  num_workers: 16
  num_warmup_steps: 500
  num_train_timesteps: 1000
  fm_shift: 1.0
  max_iters: 50000
  class_dropout_prob: 0.1
  null_emb_path: data/null_emb.pth
  scaling_factor: 0.41407
  save_freq: 10000
  grad_checkpointing: false
  nblocks_to_apply_grad_checkpointing: -1
  gradient_clip: 1.0
  resume_from: ''
  start_step: 0
  use_ema: true
  ema_rate: 0.9999
  proj_coeff: 0.5
  mask_ratio_min: 0.7
  ratio_sampling_method: mar
  use_ncl: false
  weighting_scheme: logit_normal
  logit_mean: 0
  logit_std: 1
  mode_scale: 1.29
  patch_mixer_depth: -1
  mask_ratio: 0.5
  transformer_ckpt: /root/tongs/projects/training_files_AR/emmdit_nosub_init_diffbs2/checkpoints/checkpoint-200000/model.safetensors
validation:
  validation_frequency: 1000
  seed: 0
  num_inference_timesteps: 20
  cfg: 4.5
  num_images_per_prompt: 1
optimizer:
  type: AdamW
  opt_kwargs:
    lr: 0.0001
    weight_decay: 0.03
    eps: 1.0e-10
dataset:
  use_dummy_data: false
  datasets:
  - /root/tongs/data/jDB/mds_latents_dcvae_flant5large/train
  - /root/tongs/data/jDB/mds_latents_dcvae_flant5large/valid
  - /root/tongs/data/flux_gen_data/imglatent_mds_UCSC_part0/
  - /root/tongs/data/flux_gen_data/imglatent_mds_UCSC_part1/
  - /root/tongs/data/flux_gen_data/imglatent_mds_UCSC_part2/
  - /root/tongs/data/flux_gen_data/imglatent_mds_UCSC_part3/
  - /root/tongs/data/flux_gen_data/imglatent_mds_UCSC_part4/
  - /root/tongs/data/flux_gen_data/imglatent_mds_UCSC_part5/
  - /root/tongs/data/flux_gen_data/imglatent_mds_diffdb/